name: subst
version: 0.0.1
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Text substitution in strings on the wildcard characters.
homepage: https://github.com/mezoni/subst
dependencies:
  unittest: any
