name: patsubst
version: 0.0.2
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Pattern based text substitution in strings.
homepage: https://github.com/mezoni/subst
dependencies:
  unittest: any
